import getters from './getters';
import mutations from './mutations';
import actions from './actions';

const state = {
  rooms: [
    {
      id: 0,
      name: 'Test room',
      tournament: true,
      locked: true,
      scenario: true,
      currentPlayers: 4,
      maxPlayers: 8,
      currentRound: 2,
      maxRounds: 8,
      playing: true,
    },
    {
      id: 1,
      name: 'New test room',
      tournament: true,
      locked: false,
      scenario: true,
      currentPlayers: 1,
      maxPlayers: 8,
      currentRound: 0,
      maxRounds: 8,
    },
    {
      id: 2,
      name: 'Third room bitch',
      tournament: false,
      locked: false,
      scenario: true,
      currentPlayers: 4,
      maxPlayers: 8,
      currentRound: 6,
      maxRounds: 9,
    },
    {
      id: 4,
      name: 'Fourth room bitch',
      tournament: false,
      locked: true,
      scenario: false,
      currentPlayers: 8,
      maxPlayers: 8,
      currentRound: 2,
      maxRounds: 8,
    },
    {
      id: 5,
      name: 'Test room',
      tournament: true,
      locked: true,
      scenario: true,
      currentPlayers: 4,
      maxPlayers: 8,
      currentRound: 2,
      maxRounds: 8,
    },
    {
      id: 6,
      name: 'New test room',
      tournament: true,
      locked: false,
      scenario: true,
      currentPlayers: 1,
      maxPlayers: 8,
      currentRound: 0,
      maxRounds: 8,
      playing: true,
    },
    {
      id: 7,
      name: 'Third room bitch',
      tournament: false,
      locked: false,
      scenario: true,
      currentPlayers: 4,
      maxPlayers: 8,
      currentRound: 6,
      maxRounds: 9,
    },
    {
      id: 8,
      name: 'Fourth room bitch',
      tournament: false,
      locked: true,
      scenario: false,
      currentPlayers: 8,
      maxPlayers: 8,
      currentRound: 2,
      maxRounds: 8,
    },
    {
      id: 9,
      name: 'Test room',
      tournament: true,
      locked: true,
      scenario: true,
      currentPlayers: 4,
      maxPlayers: 8,
      currentRound: 2,
      maxRounds: 8,
    },
    {
      id: 10,
      name: 'New test room',
      tournament: true,
      locked: false,
      scenario: true,
      currentPlayers: 1,
      maxPlayers: 8,
      currentRound: 0,
      maxRounds: 8,
    },
    {
      id: 11,
      name: 'Third room bitch',
      tournament: false,
      locked: false,
      scenario: true,
      currentPlayers: 4,
      maxPlayers: 8,
      currentRound: 6,
      maxRounds: 9,
      playing: true,
    },
    {
      id: 12,
      name: 'Fourth room bitch',
      tournament: false,
      locked: true,
      scenario: false,
      currentPlayers: 8,
      maxPlayers: 8,
      currentRound: 2,
      maxRounds: 8,
    },
  ],
};

export default {
  namespaced: true,
  state,
  getters,
  mutations,
  actions,
};
